import './globals.css'
import type { Metadata } from 'next'
import { Yatra_One,Imprima } from 'next/font/google'

const yatraOne=Yatra_One({
  subsets: ['latin'],
  variable:'--font-yatra',
  weight:['400']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={yatraOne.variable}>{children}</body>
    </html>
  )
}
